import { NextResponse } from "next/server";
import { requireRole } from "@/lib/auth/api";
import { prisma } from "@/lib/prisma";
import { monitoringAlertWhere, sp } from "@/lib/list-api-filters";
import { zodErrorResponse } from "@/lib/api-errors";
import { createMonitoringAlertSchema } from "@/lib/validation/monitoring-alert";
import { loadAlertLifecycleConfig } from "@/lib/alert-lifecycle-config-db";
import { resolveCreateLifecycleStatus } from "@/lib/entity-lifecycle-create-guard";
import { manualAlertCreateFields } from "@/lib/alert-source";

const alertInclude = { application: { select: { id: true, name: true } } } as const;

async function nextAlertCode(): Promise<string> {
  const rows = await prisma.monitoringAlert.findMany({ select: { alertCode: true } });
  const next = rows.reduce((max, row) => {
    const match = row.alertCode.match(/^ALT-(\d+)$/i);
    return match ? Math.max(max, Number(match[1])) : max;
  }, 0) + 1;
  return `ALT-${String(next).padStart(3, "0")}`;
}

export async function GET(req: Request) {
  const { error } = await requireRole("readonly");
  if (error) return error;

  try {
    const data = await prisma.monitoringAlert.findMany({
      where: monitoringAlertWhere(sp(req)),
      include: alertInclude,
      orderBy: { sourceOrder: "asc" },
    });
    return NextResponse.json(data);
  } catch (err) {
    console.error("[monitoring-alerts-list] query failed", {
      message: err instanceof Error ? err.message : "unknown",
    });
    return NextResponse.json({ error: "Failed to load monitoring alerts" }, { status: 500 });
  }
}

export async function POST(req: Request) {
  const { user, error } = await requireRole("editor");
  if (error) return error;

  const parsed = createMonitoringAlertSchema.safeParse(await req.json());
  if (!parsed.success) return zodErrorResponse(parsed.error);
  const body = parsed.data;

  let status = String(body.status ?? "").trim();
  let statusKey: string | undefined;
  try {
    const loaded = await loadAlertLifecycleConfig(user!.id);
    const resolved = resolveCreateLifecycleStatus(loaded.config, status, "alert");
    if (!resolved.ok) return resolved.response;
    status = resolved.status;
    statusKey = resolved.statusKey;
  } catch (err) {
    console.error("[monitoring-alerts-create] lifecycle config load failed", {
      message: err instanceof Error ? err.message : "unknown",
    });
    return NextResponse.json(
      { error: "Alert lifecycle configuration is temporarily unavailable" },
      { status: 503 }
    );
  }

  const [application, maxOrder] = await Promise.all([
    prisma.application.findUnique({ where: { id: body.applicationId }, select: { id: true } }),
    prisma.monitoringAlert.aggregate({ _max: { sourceOrder: true } }),
  ]);
  if (!application) {
    return NextResponse.json({ error: "Application not found" }, { status: 400 });
  }

  // Editor POST is always a person-created alert — ignore client source claims.
  const source = manualAlertCreateFields();
  const row = await prisma.monitoringAlert.create({
    data: {
      alertCode: await nextAlertCode(),
      timestamp: new Date(body.timestamp),
      applicationId: body.applicationId,
      departmentName: body.departmentName ?? null,
      alertType: body.alertType,
      alertSource: source.alertSource,
      autoGenerated: source.autoGenerated,
      notes: body.notes ?? null,
      severity: body.severity,
      metric: body.metric,
      threshold: body.threshold ?? null,
      currentValue: body.currentValue ?? null,
      status,
      statusKey,
      assignedTo: body.assignedTo ?? null,
      environmentName: body.environmentName,
      sourceOrder: (maxOrder._max.sourceOrder ?? 0) + 1,
    },
    include: alertInclude,
  });
  return NextResponse.json(row, { status: 201 });
}
