import { z } from "zod";

const optionalNullableString = z.union([z.string().trim().max(2000), z.null()]).optional();
const optionalNullableDate = z.union([z.string().trim().min(1).max(40), z.null()]).optional();
const optionalNullableInt = z.union([z.number().int().min(0).max(3650), z.null()]).optional();

export const LEAVE_TYPES = ["Annual", "Bereavement", "Medical", "Parental", "Personal", "Study"] as const;

/** POST /api/leaves — create fields only; record IDs are generated by the server. */
export const createLeaveSchema = z
  .object({
    userId: z.string().trim().min(1).max(64),
    leaveStart: z.string().date(),
    leaveEnd: z.string().date(),
    leaveType: z.string().trim().min(1).max(120),
    days: z.number().int().min(1).max(3650),
    riskImpact: z.union([z.string().trim().max(2000), z.null()]).optional(),
    riskScore: z.number().int().min(0).max(10).optional(),
    releaseIds: z.array(z.string().trim().min(1).max(64)).max(100).optional(),
  })
  .strict()
  .refine((value) => value.leaveEnd >= value.leaveStart, {
    path: ["leaveEnd"],
    message: "End date must be on or after start date",
  });

export type CreateLeaveInput = z.infer<typeof createLeaveSchema>;

/**
 * PATCH /api/leaves/[id] — allowlisted fields only.
 * leaveCode (Leave ID) and employee userId are immutable from this endpoint.
 */
export const patchLeaveSchema = z
  .object({
    leaveType: z.string().trim().min(1).max(120).optional(),
    leaveStart: optionalNullableDate,
    leaveEnd: optionalNullableDate,
    days: optionalNullableInt,
    riskImpact: optionalNullableString,
    riskScore: z.union([z.number().int().min(0).max(10), z.null()]).optional(),
  })
  .strict();

export type PatchLeaveInput = z.infer<typeof patchLeaveSchema>;
