/**
 * Run: npx tsx --test lib/validation/monitoring-alert-source.test.ts
 */
import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { createMonitoringAlertSchema } from "./monitoring-alert";
import { manualAlertCreateFields } from "../alert-source";

const validBody = {
  timestamp: "2026-08-18T10:00:00.000Z",
  applicationId: "app_1",
  alertType: "Warning",
  severity: "Critical",
  metric: "cpu",
  environmentName: "UAT",
  status: "Pending",
};

describe("createMonitoringAlertSchema source fields", () => {
  it("accepts an explicit Manual create payload", () => {
    const parsed = createMonitoringAlertSchema.safeParse({
      ...validBody,
      ...manualAlertCreateFields(),
    });
    assert.equal(parsed.success, true);
    if (!parsed.success) return;
    assert.equal(parsed.data.autoGenerated, false);
    assert.equal(parsed.data.alertSource, "Manual");
  });

  it("rejects an unknown alertSource", () => {
    const parsed = createMonitoringAlertSchema.safeParse({
      ...validBody,
      alertSource: "Connector",
    });
    assert.equal(parsed.success, false);
  });
});
