/**
 * Skip auto-creating an alert when one is already open or being worked
 * for the same application + metric + environment.
 */
import { prisma } from "@/lib/prisma";
import { createDefaultAlertLifecycleConfig } from "@/lib/alert-lifecycle-config";
import { loadAlertLifecycleConfig } from "@/lib/alert-lifecycle-config-db";
import { enabledStatusMatchValues } from "@/lib/lifecycle-status-roles";
import type { AlertSource } from "@/lib/alert-sources";

export type AlertRepeatCondition = {
  applicationId: string;
  metric: string;
  environmentName: string;
};

/**
 * Status values (label + key) that should block a duplicate auto-create.
 * Intake (already firing) and statuses flagged “stops repeat alerts”.
 */
export async function repeatSuppressingStatusValues(
  clerkUserId?: string | null
): Promise<string[]> {
  const config = clerkUserId
    ? (await loadAlertLifecycleConfig(clerkUserId)).config
    : createDefaultAlertLifecycleConfig();
  return enabledStatusMatchValues(
    config.statuses,
    (status) => status.isIntake || Boolean(status.suppressesRepeatAlerts)
  );
}

/**
 * True when an existing alert for this condition is still Active or being worked.
 * @param condition - Application + metric + environment
 * @param clerkUserId - Optional owner scope for the live graph
 */
export async function findRepeatSuppressingAlert(
  condition: AlertRepeatCondition,
  clerkUserId?: string | null
): Promise<{ alertCode: string } | null> {
  const values = await repeatSuppressingStatusValues(clerkUserId);
  if (values.length === 0) return null;
  const existing = await prisma.monitoringAlert.findFirst({
    where: {
      applicationId: condition.applicationId,
      metric: condition.metric,
      environmentName: condition.environmentName,
      OR: [{ status: { in: values } }, { statusKey: { in: values } }],
    },
    select: { alertCode: true },
  });
  return existing;
}

/**
 * Next unique alertCode when the stable base already exists as a closed row.
 * @param base - Stable code (e.g. STALE-BLK-0001)
 */
export async function nextRepeatAlertCode(base: string): Promise<string> {
  const existing = await prisma.monitoringAlert.findUnique({
    where: { alertCode: base },
    select: { id: true },
  });
  if (!existing) return base;
  const rows = await prisma.monitoringAlert.findMany({
    where: { alertCode: { startsWith: `${base}-` } },
    select: { alertCode: true },
  });
  const prefix = `${base}-`;
  const next =
    rows.reduce((max, row) => {
      if (!row.alertCode.startsWith(prefix)) return max;
      const n = Number(row.alertCode.slice(prefix.length));
      return Number.isInteger(n) ? Math.max(max, n) : max;
    }, 1) + 1;
  return `${base}-${next}`;
}

export type CreateAutoAlertResult = "created" | "suppressed";

/**
 * Create a system-generated alert, or skip when a live one already covers
 * the same application + metric + environment.
 */
export async function createAutoMonitoringAlert(args: {
  clerkUserId?: string | null;
  baseAlertCode: string;
  applicationId: string;
  departmentName?: string | null;
  alertType: string;
  alertSource: AlertSource;
  severity: string;
  metric: string;
  threshold?: string | null;
  currentValue?: string | null;
  environmentName: string;
  assignedTo?: string | null;
}): Promise<CreateAutoAlertResult> {
  const blocking = await findRepeatSuppressingAlert(
    {
      applicationId: args.applicationId,
      metric: args.metric,
      environmentName: args.environmentName,
    },
    args.clerkUserId
  );
  if (blocking) return "suppressed";

  const config = args.clerkUserId
    ? (await loadAlertLifecycleConfig(args.clerkUserId)).config
    : createDefaultAlertLifecycleConfig();
  const intake =
    config.statuses.find((status) => status.enabled && status.isIntake) ??
    config.statuses.find((status) => status.enabled);
  const alertCode = await nextRepeatAlertCode(args.baseAlertCode);
  const maxOrder = await prisma.monitoringAlert.aggregate({
    _max: { sourceOrder: true },
  });
  await prisma.monitoringAlert.create({
    data: {
      alertCode,
      timestamp: new Date(),
      applicationId: args.applicationId,
      departmentName: args.departmentName ?? null,
      alertType: args.alertType,
      alertSource: args.alertSource,
      autoGenerated: true,
      severity: args.severity,
      metric: args.metric,
      threshold: args.threshold ?? null,
      currentValue: args.currentValue ?? null,
      status: intake?.label ?? "Active",
      statusKey: intake?.key ?? "pending",
      assignedTo: args.assignedTo ?? null,
      environmentName: args.environmentName,
      sourceOrder: (maxOrder._max.sourceOrder ?? 0) + 1,
    },
  });
  return "created";
}
