/**
 * How a MonitoringAlert row was created.
 * Manual = person-created (Release page / Alerts list). System = cron, hooks, seed.
 */

export const ALERT_SOURCE_MANUAL = "Manual" as const;
export const ALERT_SOURCE_SYSTEM = "System" as const;

export const ALERT_SOURCES = [ALERT_SOURCE_MANUAL, ALERT_SOURCE_SYSTEM] as const;
export type AlertSource = (typeof ALERT_SOURCES)[number];

export type AlertSourceCreateFields = {
  autoGenerated: boolean;
  alertSource: AlertSource;
};

/**
 * Fields for a person-created alert. Used by POST /api/monitoring-alerts
 * and every Manual create form.
 */
export function manualAlertCreateFields(): AlertSourceCreateFields {
  return { autoGenerated: false, alertSource: ALERT_SOURCE_MANUAL };
}

/**
 * Fields for cron / lifecycle-hook / seed alerts.
 */
export function systemAlertCreateFields(): AlertSourceCreateFields {
  return { autoGenerated: true, alertSource: ALERT_SOURCE_SYSTEM };
}

/**
 * True when stored values represent a person-created alert.
 */
export function isManualAlert(row: {
  autoGenerated?: boolean | null;
  alertSource?: string | null;
}): boolean {
  if (row.alertSource?.trim().toLocaleLowerCase() === ALERT_SOURCE_MANUAL.toLocaleLowerCase()) {
    return true;
  }
  return row.autoGenerated === false;
}
