/**
 * Per-user Alerts lifecycle configuration (statuses + transitions + types).
 * Matches the enterprise Alerts sheet: 7 statuses, Closed sole terminal.
 * No auto-expiry timer — Expired is a retired label, not a destination.
 */
export const ALERT_LIFECYCLE_ENFORCEMENTS = ["flexible", "required"] as const;
export type AlertLifecycleEnforcement =
  (typeof ALERT_LIFECYCLE_ENFORCEMENTS)[number];

export const ALERT_EDIT_MODES = [
  "full",
  "limited",
  "read_only",
  "immutable",
] as const;
export type AlertEditMode = (typeof ALERT_EDIT_MODES)[number];

/** Display-only accountable role from the sheet — not Clerk-enforced. */
export const ALERT_STATUS_OWNER_HINT: Readonly<Record<string, string>> = {
  active: "Alert Recipient",
  acknowledged: "Alert Recipient",
  investigating: "Alert Recipient",
  escalated: "Manager",
  resolved: "Alert Recipient",
  suppressed: "Admin",
  closed: "N/A",
};

export type AlertLifecycleStatusConfig = {
  key: string;
  label: string;
  sortOrder: number;
  terminal: boolean;
  enabled: boolean;
  isSystem: boolean;
  editMode: AlertEditMode;
  /** Cascade / notes shown in settings. */
  cascadeEffect: string;
  /** New alert records land here. */
  isIntake: boolean;
};

export type AlertLifecycleTransitionConfig = {
  fromKey: string;
  toKey: string;
  enabled: boolean;
  enforcement: AlertLifecycleEnforcement;
  isSystem: boolean;
  sortOrder: number;
};

export type AlertTypeConfig = {
  key: string;
  label: string;
  sortOrder: number;
  enabled: boolean;
  isSystem: boolean;
  description: string;
};

export type AlertLifecycleConfig = {
  statuses: AlertLifecycleStatusConfig[];
  transitions: AlertLifecycleTransitionConfig[];
  types: AlertTypeConfig[];
};

export const MAX_ALERT_LIFECYCLE_STATUSES = 20;
export const MAX_ALERT_LIFECYCLE_TRANSITIONS = 80;
export const MAX_ALERT_TYPES = 20;

function status(
  partial: Omit<AlertLifecycleStatusConfig, "isIntake">
): AlertLifecycleStatusConfig {
  return {
    ...partial,
    isIntake: partial.key === "active",
  };
}

export const DEFAULT_ALERT_LIFECYCLE_STATUSES: readonly AlertLifecycleStatusConfig[] =
  [
    status({
      key: "active",
      label: "Active",
      sortOrder: 10,
      terminal: false,
      enabled: true,
      isSystem: true,
      editMode: "full",
      cascadeEffect:
        "Starting status — auto-generated by monitoring or workflow engines",
    }),
    status({
      key: "acknowledged",
      label: "Acknowledged",
      sortOrder: 20,
      terminal: false,
      enabled: true,
      isSystem: true,
      editMode: "limited",
      cascadeEffect: "Recipient confirmed receipt — stops repeat alerts",
    }),
    status({
      key: "investigating",
      label: "Investigating",
      sortOrder: 30,
      terminal: false,
      enabled: true,
      isSystem: true,
      editMode: "full",
      cascadeEffect: "Being actively investigated",
    }),
    status({
      key: "escalated",
      label: "Escalated",
      sortOrder: 40,
      terminal: false,
      enabled: true,
      isSystem: true,
      editMode: "full",
      cascadeEffect: "Raised to a higher level",
    }),
    status({
      key: "resolved",
      label: "Resolved",
      sortOrder: 50,
      terminal: false,
      enabled: true,
      isSystem: true,
      editMode: "limited",
      cascadeEffect: "Handled — audit trail captured. Archive to Closed when done.",
    }),
    status({
      key: "suppressed",
      label: "Suppressed",
      sortOrder: 60,
      terminal: false,
      enabled: true,
      isSystem: true,
      editMode: "full",
      cascadeEffect:
        "Quiet-hours suppression (NOTIF-15). Can return to Active or archive to Closed.",
    }),
    status({
      key: "closed",
      label: "Closed",
      sortOrder: 70,
      terminal: true,
      enabled: true,
      isSystem: true,
      editMode: "immutable",
      cascadeEffect: "Sole terminal — no further action required",
    }),
  ];

function edge(
  fromKey: string,
  toKey: string,
  sortOrder: number
): AlertLifecycleTransitionConfig {
  return {
    fromKey,
    toKey,
    enabled: true,
    enforcement: "flexible",
    isSystem: true,
    sortOrder,
  };
}

export const DEFAULT_ALERT_LIFECYCLE_TRANSITIONS: readonly AlertLifecycleTransitionConfig[] =
  [
    edge("active", "acknowledged", 10),
    edge("active", "suppressed", 20),
    edge("acknowledged", "investigating", 10),
    edge("acknowledged", "resolved", 20),
    edge("investigating", "resolved", 10),
    edge("investigating", "escalated", 20),
    edge("escalated", "investigating", 10),
    edge("escalated", "resolved", 20),
    edge("resolved", "closed", 10),
    edge("suppressed", "active", 10),
    edge("suppressed", "closed", 20),
  ];

export const DEFAULT_ALERT_TYPES: readonly AlertTypeConfig[] = [
  {
    key: "reminder",
    label: "Reminder",
    sortOrder: 10,
    enabled: true,
    isSystem: true,
    description: "Scheduled or due-date reminder",
  },
  {
    key: "warning",
    label: "Warning",
    sortOrder: 20,
    enabled: true,
    isSystem: true,
    description: "Threshold or risk warning",
  },
  {
    key: "escalation",
    label: "Escalation",
    sortOrder: 30,
    enabled: true,
    isSystem: true,
    description: "Escalated attention required",
  },
  {
    key: "notification",
    label: "Notification",
    sortOrder: 40,
    enabled: true,
    isSystem: true,
    description: "Informational notification",
  },
];

/**
 * Fresh default alert lifecycle graph + types.
 * @returns Independent deep copy of the enterprise default.
 */
export function createDefaultAlertLifecycleConfig(): AlertLifecycleConfig {
  return {
    statuses: DEFAULT_ALERT_LIFECYCLE_STATUSES.map((s) => ({ ...s })),
    transitions: DEFAULT_ALERT_LIFECYCLE_TRANSITIONS.map((t) => ({ ...t })),
    types: DEFAULT_ALERT_TYPES.map((t) => ({ ...t })),
  };
}

/**
 * Starting status for new MonitoringAlert rows (create + system hooks).
 * @param config - Live graph; defaults to the sheet.
 */
export function alertIntakeStatus(
  config: AlertLifecycleConfig = createDefaultAlertLifecycleConfig()
): { key: string; label: string } {
  const intake =
    config.statuses.find((s) => s.enabled && s.isIntake) ??
    config.statuses.find((s) => s.key === "active");
  return { key: intake?.key ?? "active", label: intake?.label ?? "Active" };
}

/**
 * Validate alert lifecycle graph before persistence / enforcement.
 * @returns null when valid, otherwise a user-safe error string.
 */
export function validateAlertLifecycleConfig(
  config: AlertLifecycleConfig
): string | null {
  if (
    config.statuses.length < 1 ||
    config.statuses.length > MAX_ALERT_LIFECYCLE_STATUSES
  ) {
    return `Alert lifecycle must contain 1–${MAX_ALERT_LIFECYCLE_STATUSES} statuses`;
  }
  if (config.transitions.length > MAX_ALERT_LIFECYCLE_TRANSITIONS) {
    return `Alert lifecycle cannot exceed ${MAX_ALERT_LIFECYCLE_TRANSITIONS} transitions`;
  }
  if (!Array.isArray(config.types) || config.types.length > MAX_ALERT_TYPES) {
    return `Alert lifecycle cannot exceed ${MAX_ALERT_TYPES} types`;
  }
  const keys = new Set<string>();
  const labels = new Set<string>();
  for (const item of config.statuses) {
    if (!/^[a-z][a-z0-9_]{0,39}$/.test(item.key)) {
      return `Invalid alert status key: ${item.key}`;
    }
    if (!item.label.trim()) return `Invalid label for ${item.key}`;
    if (keys.has(item.key)) return `Duplicate status key: ${item.key}`;
    const lower = item.label.trim().toLocaleLowerCase();
    if (labels.has(lower)) return `Duplicate status label: ${item.label}`;
    if (!ALERT_EDIT_MODES.includes(item.editMode)) {
      return `Invalid editMode for ${item.key}`;
    }
    keys.add(item.key);
    labels.add(lower);
  }
  const byKey = new Map(config.statuses.map((s) => [s.key, s]));
  const edges = new Set<string>();
  for (const item of config.transitions) {
    const from = byKey.get(item.fromKey);
    const to = byKey.get(item.toKey);
    if (!from) return `Unknown transition source: ${item.fromKey}`;
    if (!to) return `Unknown transition target: ${item.toKey}`;
    if (item.enabled && (from.terminal || !from.enabled || !to.enabled)) {
      return `Enabled transition ${item.fromKey} → ${item.toKey} uses a terminal or disabled status`;
    }
    if (!ALERT_LIFECYCLE_ENFORCEMENTS.includes(item.enforcement)) {
      return `Invalid enforcement for ${item.fromKey} → ${item.toKey}`;
    }
    const edgeId = `${item.fromKey}:${item.toKey}`;
    if (edges.has(edgeId)) return `Duplicate transition: ${edgeId}`;
    edges.add(edgeId);
  }
  const typeKeys = new Set<string>();
  for (const type of config.types) {
    if (!/^[a-z][a-z0-9_]{0,39}$/.test(type.key)) {
      return `Invalid alert type key: ${type.key}`;
    }
    if (!type.label.trim()) return `Invalid label for type ${type.key}`;
    if (typeKeys.has(type.key)) return `Duplicate type key: ${type.key}`;
    typeKeys.add(type.key);
  }
  return null;
}

function coerceBoolean(value: unknown, fallback: boolean): boolean {
  return typeof value === "boolean" ? value : fallback;
}

/**
 * Normalize stored JSON; field-coerce only (reconcile runs on load/save).
 * @param raw - Persisted snapshot or null.
 */
export function normalizeAlertLifecycleConfig(raw: unknown): AlertLifecycleConfig {
  const defaults = createDefaultAlertLifecycleConfig();
  if (
    !raw ||
    typeof raw !== "object" ||
    !Array.isArray((raw as AlertLifecycleConfig).statuses) ||
    !Array.isArray((raw as AlertLifecycleConfig).transitions) ||
    !Array.isArray((raw as AlertLifecycleConfig).types)
  ) {
    return defaults;
  }
  const candidate = raw as AlertLifecycleConfig;
  const mapped: AlertLifecycleConfig = {
    statuses: candidate.statuses.map((s) => {
      const def = defaults.statuses.find((d) => d.key === s.key);
      return {
        key: s.key,
        label: s.label,
        sortOrder: s.sortOrder,
        terminal: Boolean(s.terminal),
        enabled: s.enabled !== false,
        isSystem: Boolean(s.isSystem),
        editMode: ALERT_EDIT_MODES.includes(s.editMode)
          ? s.editMode
          : (def?.editMode ?? "full"),
        cascadeEffect: s.cascadeEffect ?? def?.cascadeEffect ?? "",
        isIntake: coerceBoolean(s.isIntake, def?.isIntake ?? false),
      };
    }),
    transitions: candidate.transitions.map((t) => ({
      fromKey: t.fromKey,
      toKey: t.toKey,
      enabled: t.enabled !== false,
      enforcement: ALERT_LIFECYCLE_ENFORCEMENTS.includes(t.enforcement)
        ? t.enforcement
        : "flexible",
      isSystem: Boolean(t.isSystem),
      sortOrder: t.sortOrder,
    })),
    types: candidate.types.map((t) => ({ ...t })),
  };
  if (!validateAlertLifecycleConfig(mapped)) return mapped;
  return defaults;
}

export const DEFAULT_ALERT_LIFECYCLE_CONFIG = createDefaultAlertLifecycleConfig();
