/**
 * Run: npx tsx --test lib/alert-source.test.ts
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import {
  ALERT_SOURCE_MANUAL,
  ALERT_SOURCE_SYSTEM,
  isManualAlert,
  manualAlertCreateFields,
  systemAlertCreateFields,
} from "./alert-source";

describe("alert source create fields", () => {
  it("Manual create is never auto-generated", () => {
    assert.deepEqual(manualAlertCreateFields(), {
      autoGenerated: false,
      alertSource: ALERT_SOURCE_MANUAL,
    });
  });

  it("System create is auto-generated", () => {
    assert.deepEqual(systemAlertCreateFields(), {
      autoGenerated: true,
      alertSource: ALERT_SOURCE_SYSTEM,
    });
  });
});

describe("isManualAlert", () => {
  it("treats alertSource Manual as person-created even if autoGenerated is missing", () => {
    assert.equal(isManualAlert({ alertSource: "Manual" }), true);
    assert.equal(isManualAlert({ autoGenerated: false }), true);
  });

  it("treats System / auto-generated rows as not Manual", () => {
    assert.equal(isManualAlert({ autoGenerated: true, alertSource: "System" }), false);
    assert.equal(isManualAlert({}), false);
  });
});

describe("alert source column backfill", () => {
  it("fills NULL alertSource then enforces NOT NULL (Prisma P2032 regression)", () => {
    const root = join(dirname(fileURLToPath(import.meta.url)), "..");
    const script = readFileSync(join(root, "scripts/add-alert-source-columns.ts"), "utf8");
    assert.match(script, /WHERE "alertSource" IS NULL/);
    assert.match(script, /ALTER COLUMN "alertSource" SET NOT NULL/);
    assert.match(script, /WHERE "autoGenerated" IS NULL/);
    assert.match(script, /ALTER COLUMN "autoGenerated" SET NOT NULL/);
  });
});
