/**
 * Additive MonitoringAlert.autoGenerated + alertSource columns.
 * Do not use `prisma db push` — the vendored schema is behind the live DB.
 *
 * ADD COLUMN IF NOT EXISTS is a no-op when the column already exists as
 * nullable (e.g. a prior partial apply). Existing NULL rows then fail Prisma
 * reads (P2032). Always backfill, then enforce NOT NULL + defaults.
 */
import "@/lib/load-db-env-for-tests";
import { prisma } from "@/lib/prisma";

async function main(): Promise<void> {
  await prisma.$executeRawUnsafe(
    `ALTER TABLE "MonitoringAlert" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN`
  );
  await prisma.$executeRawUnsafe(
    `ALTER TABLE "MonitoringAlert" ADD COLUMN IF NOT EXISTS "alertSource" TEXT`
  );
  await prisma.$executeRawUnsafe(
    `UPDATE "MonitoringAlert" SET "autoGenerated" = true WHERE "autoGenerated" IS NULL`
  );
  await prisma.$executeRawUnsafe(
    `UPDATE "MonitoringAlert" SET "alertSource" = 'System' WHERE "alertSource" IS NULL`
  );
  await prisma.$executeRawUnsafe(
    `ALTER TABLE "MonitoringAlert" ALTER COLUMN "autoGenerated" SET DEFAULT true`
  );
  await prisma.$executeRawUnsafe(
    `ALTER TABLE "MonitoringAlert" ALTER COLUMN "alertSource" SET DEFAULT 'System'`
  );
  await prisma.$executeRawUnsafe(
    `ALTER TABLE "MonitoringAlert" ALTER COLUMN "autoGenerated" SET NOT NULL`
  );
  await prisma.$executeRawUnsafe(
    `ALTER TABLE "MonitoringAlert" ALTER COLUMN "alertSource" SET NOT NULL`
  );
}

main()
  .catch((err) => {
    console.error("[add-alert-source-columns] failed", {
      message: err instanceof Error ? err.message : "unknown",
    });
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
