/**
 * Additive Alert notes / source / autoGenerated columns. Do not use
 * `prisma db push` — the vendored schema is behind the live DB and would
 * drop organizationId / v2 tables.
 */
import "@/lib/load-db-env-for-tests";
import { prisma } from "@/lib/prisma";

const STATEMENTS = [
  `ALTER TABLE "MonitoringAlert" ADD COLUMN IF NOT EXISTS "notes" TEXT`,
  `ALTER TABLE "MonitoringAlert" ADD COLUMN IF NOT EXISTS "alertSource" TEXT`,
  `ALTER TABLE "MonitoringAlert" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false`,
] as const;

async function main(): Promise<void> {
  for (const sql of STATEMENTS) {
    await prisma.$executeRawUnsafe(sql);
  }
}

main()
  .catch((err) => {
    console.error("[add-alert-lifecycle-columns] failed", {
      message: err instanceof Error ? err.message : "unknown",
    });
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
