"use client";

import { useCallback, useEffect, useState } from "react";
import { ProgressLink } from "@/components/layout/NavigationProgress";
import { StatusBadge } from "@/components/badges/StatusBadge";
import { MonitoringAlertFormModal } from "@/components/monitoring-alerts/MonitoringAlertFormModal";
import { ReleaseRelatedListFrame } from "@/components/releases/ReleaseRelatedListFrame";
import { safeFetchJson } from "@/lib/safe-fetch";
import { isManualAlert } from "@/lib/alert-source";

type LiveAlert = {
  id: string;
  alertCode: string;
  alertType: string;
  severity: string;
  status: string;
  metric: string;
  environmentName: string;
  autoGenerated?: boolean;
  alertSource?: string;
  application: { id: string; name: string };
};

type Props = {
  applications: { id: string; name: string }[];
  departmentId: string;
  canEdit?: boolean;
};

/**
 * Alerts for this release's application(s). Manual create sets source fields.
 */
export function DbReleaseAlertList({
  applications,
  departmentId,
  canEdit = false,
}: Props) {
  const [rows, setRows] = useState<LiveAlert[] | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [reloadKey, setReloadKey] = useState(0);
  const primaryApp = applications[0];
  const applicationIdsKey = applications.map((app) => app.id).sort().join(",");

  const reload = useCallback(() => {
    setReloadKey((key) => key + 1);
  }, []);

  useEffect(() => {
    const ids = applicationIdsKey ? applicationIdsKey.split(",") : [];
    if (ids.length === 0) {
      setRows([]);
      return;
    }
    let cancelled = false;
    setRows(null);
    void (async () => {
      const results = await Promise.all(
        ids.map((id) =>
          safeFetchJson<LiveAlert[]>(
            `/api/monitoring-alerts?app=${encodeURIComponent(id)}`,
            { label: "release-live-alerts" }
          )
        )
      );
      if (cancelled) return;
      const merged = new Map<string, LiveAlert>();
      for (const result of results) {
        if (!result.ok) continue;
        for (const row of result.data) merged.set(row.id, row);
      }
      setRows([...merged.values()]);
    })();
    return () => {
      cancelled = true;
    };
  }, [applicationIdsKey, reloadKey]);

  const emptyLabel =
    applications.length === 0
      ? "No applications on this release — alerts are scoped to applications"
      : "No alerts linked";

  return (
    <>
      <ReleaseRelatedListFrame
        heading="Application alerts"
        addLabel="Add Alert"
        canEdit={canEdit && Boolean(primaryApp)}
        onAdd={() => setModalOpen(true)}
        loading={rows == null}
        loadingLabel="Loading alerts…"
        emptyLabel={emptyLabel}
        hasItems={Boolean(rows?.length)}
      >
        <ul className="space-y-2">
          {(rows ?? []).map((row) => (
            <li
              key={row.id}
              className="space-y-1.5 rounded-lg bg-gray-50/80 px-3 py-2.5 dark:bg-white/5"
            >
              <div className="flex flex-wrap items-center gap-2">
                <ProgressLink
                  href={`/monitoring-alerts/${row.id}`}
                  className="font-mono text-xs font-semibold text-brand-600 hover:underline dark:text-brand-400"
                >
                  {row.alertCode}
                </ProgressLink>
                <StatusBadge status={row.status} />
                <span className="text-[10px] text-gray-500 dark:text-white/50">{row.severity}</span>
                <span className="text-[10px] text-gray-500 dark:text-white/50">{row.alertType}</span>
                <span className="text-[10px] font-medium uppercase tracking-wide text-slate-400">
                  {isManualAlert(row) ? "Manual" : row.alertSource || "System"}
                </span>
              </div>
              <p className="text-sm text-gray-700 dark:text-white/80">
                {row.application.name} · {row.metric}
              </p>
              <p className="text-xs text-gray-500 dark:text-white/50">{row.environmentName}</p>
            </li>
          ))}
        </ul>
      </ReleaseRelatedListFrame>
      {primaryApp ? (
        <MonitoringAlertFormModal
          open={modalOpen}
          onClose={() => setModalOpen(false)}
          onCreated={reload}
          lockTo={{ departmentId, applicationId: primaryApp.id }}
        />
      ) : null}
    </>
  );
}
